FROM fluent/fluentd:v1.17-1

USER root

RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install --no-document fluent-plugin-elasticsearch \
#  && sudo gem install --no-document faraday-net_http -v 3.0.2 \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent